/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9fe',
        "surface-dim": '#dad9de',
        "surface-bright": '#f9f9fe',
        "surface-container-lowest": '#ffffff',
        "surface-container-low": '#f4f3f8',
        "surface-container": '#eeedf2',
        "surface-container-high": '#e8e8ed',
        "surface-container-highest": '#e2e2e7',
        "on-surface": '#1a1c1f',
        "on-surface-variant": '#43474f',
        "inverse-surface": '#2f3034',
        "inverse-on-surface": '#f1f0f5',
        outline: '#737780',
        "outline-variant": '#c3c6d1',
        "surface-tint": '#3a5f94',
        primary: '#001e40',
        "on-primary": '#ffffff',
        "primary-container": '#003366',
        "on-primary-container": '#799dd6',
        "inverse-primary": '#a7c8ff',
        secondary: '#0059bb',
        "on-secondary": '#ffffff',
        "secondary-container": '#0070ea',
        "on-secondary-container": '#fefcff',
        tertiary: '#755b00',
        "on-tertiary": '#ffffff',
        "tertiary-container": '#caa747',
        "on-tertiary-container": '#503d00',
        error: '#ba1a1a',
        "on-error": '#ffffff',
        "error-container": '#ffdad6',
        "on-error-container": '#93000a',
        "primary-fixed": '#d5e3ff',
        "primary-fixed-dim": '#a7c8ff',
        "on-primary-fixed": '#001b3c',
        "on-primary-fixed-variant": '#1f477b',
        "secondary-fixed": '#d8e2ff',
        "secondary-fixed-dim": '#adc7ff',
        "on-secondary-fixed": '#001a41',
        "on-secondary-fixed-variant": '#004493',
        "tertiary-fixed": '#ffdf91',
        "tertiary-fixed-dim": '#e8c25f',
        "on-tertiary-fixed": '#241a00',
        "on-tertiary-fixed-variant": '#594400',
        background: '#f9f9fe',
        "on-background": '#1a1c1f',
        "surface-variant": '#e2e2e7',
      },
      fontFamily: {
        headline: ['Hanken Grotesk', 'sans-serif'],
        display: ['Hanken Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        "security-numeric": ["Hanken Grotesk", 'sans-serif'],
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px"
      },
      spacing: {
        gutter: "16px",
        "stack-sm": "4px",
        "stack-md": "12px",
        base: "8px",
        "stack-lg": "32px",
        "margin-mobile": "24px"
      },
      fontSize: {
        "body-md": ["14px", {lineHeight: "20px", fontWeight: "400"}],
        "label-caps": ["12px", {lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600"}],
        "headline-md": ["24px", {lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600"}],
        "display-lg": ["34px", {lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700"}],
        "security-numeric": ["20px", {lineHeight: "24px", letterSpacing: "0.1em", fontWeight: "500"}],
        "body-lg": ["16px", {lineHeight: "24px", fontWeight: "400"}]
      }
    },
  },
  plugins: [],
}
